# Generated by Django 4.2 on 2023-04-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('singer_name', models.CharField(max_length=100)),
                ('song_image', models.ImageField(upload_to='song_image/')),
                ('song_audio', models.FileField(upload_to='song_audio/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
